#!/usr/bin/env python3
"""
Check if the hexadecimal folder ID appears in the DICOM header
"""

import pydicom
from pathlib import Path

# Read a DICOM file from the folder
dicom_file = Path('/Users/paul/Projects/STAGE_Study/data/raw/Anon11271/100119A7/100119A8/10011A2A/10011A2B')
target_hex_id = '10011A2A'

print(f"Searching for hex ID '{target_hex_id}' in DICOM header...")
print("=" * 80)

dcm = pydicom.dcmread(dicom_file)

# Convert hex to decimal to check both formats
hex_as_decimal = int(target_hex_id, 16)
print(f"Hex ID: {target_hex_id}")
print(f"Decimal equivalent: {hex_as_decimal}")
print("=" * 80)

# List of UID and ID fields to check
id_fields = [
    'SOPInstanceUID',
    'SeriesInstanceUID',
    'StudyInstanceUID',
    'FrameOfReferenceUID',
    'SOPClassUID',
    'MediaStorageSOPInstanceUID',
    'InstanceNumber',
    'SeriesNumber',
    'StudyID',
    'AccessionNumber',
    'PatientID',
    'ImageID',
    'InstanceCreatorUID',
    'ReferencedFileID',
]

print("\n🔍 Checking ID/UID fields:")
print("-" * 80)

found_in_fields = []

for field in id_fields:
    if hasattr(dcm, field):
        value = getattr(dcm, field)
        value_str = str(value)

        # Check if hex ID appears anywhere
        if target_hex_id.lower() in value_str.lower():
            found_in_fields.append((field, value))
            print(f"✓ FOUND in {field}: {value}")
        elif str(hex_as_decimal) in value_str:
            found_in_fields.append((field, value))
            print(f"✓ FOUND (decimal) in {field}: {value}")

if not found_in_fields:
    print("✗ Hex ID not found in standard ID/UID fields")

# Now let's search ALL fields
print("\n\n🔍 Searching ALL DICOM tags:")
print("-" * 80)

all_found = []
for elem in dcm:
    value_str = str(elem.value)
    if target_hex_id.lower() in value_str.lower():
        all_found.append((elem.tag, elem.name, elem.value))
        print(f"✓ FOUND in {elem.name} ({elem.tag}): {elem.value}")
    elif str(hex_as_decimal) in value_str:
        all_found.append((elem.tag, elem.name, elem.value))
        print(f"✓ FOUND (decimal) in {elem.name} ({elem.tag}): {elem.value}")

if not all_found:
    print("✗ Hex ID not found in ANY DICOM tag")

# Let's also check the DICOMDIR to see where this ID comes from
print("\n\n🔍 Checking DICOMDIR structure:")
print("-" * 80)

dicomdir_path = Path('/Users/paul/Projects/STAGE_Study/data/raw/Anon11271/DICOMDIR')
dicomdir = pydicom.dcmread(dicomdir_path)

# Find our series
for patient in dicomdir.patient_records:
    for study in patient.children:
        for series in study.children:
            if series.SeriesNumber == 15:  # We know this is series 15
                print(f"\nSeries 15 found in DICOMDIR")
                print(f"Series UID: {series.SeriesInstanceUID}")

                # Check the first image reference
                if hasattr(series, 'children') and len(series.children) > 0:
                    first_image = series.children[0]

                    print(f"\nFirst image record:")
                    print(f"  Referenced File ID: {first_image.ReferencedFileID}")
                    print(f"  Referenced SOP Instance UID: {first_image.ReferencedSOPInstanceUIDInFile}")

                    # Check all attributes of the image record
                    print(f"\n  Image record attributes:")
                    for elem in first_image:
                        if 'UID' in elem.name or 'ID' in elem.name or 'Number' in elem.name:
                            print(f"    {elem.name}: {elem.value}")

print("\n" + "=" * 80)
print("\n📊 CONCLUSION:")
print("-" * 80)

if found_in_fields or all_found:
    print(f"The hex ID '{target_hex_id}' WAS FOUND in DICOM header fields")
else:
    print(f"The hex ID '{target_hex_id}' is NOT stored in the DICOM header")
    print("It is likely a DICOMDIR filesystem reference only")
    print("\nThis means:")
    print("  • The hex ID is generated by the PACS/imaging system for file organization")
    print("  • It serves as a directory structure reference in DICOMDIR")
    print("  • The actual DICOM data uses standard UIDs (SOPInstanceUID, etc.)")
    print("  • It's NOT a persistent identifier across different DICOM exports")
