#!/usr/bin/env python3
"""
Compare SeriesInstanceUID vs SeriesNumber in DICOM data
"""

import pydicom
from pathlib import Path

subject_dir = Path('/Users/paul/Projects/STAGE_Study/data/raw/Anon11271')
dicomdir_path = subject_dir / 'DICOMDIR'

print("=" * 100)
print("SERIES IDENTIFIERS: SeriesInstanceUID vs SeriesNumber")
print("=" * 100)

dicomdir = pydicom.dcmread(str(dicomdir_path))

print("\nExamining all series in Anon11271:\n")

series_data = []

for patient in dicomdir.patient_records:
    for study in patient.children:
        for series in study.children:
            series_num = getattr(series, 'SeriesNumber', 'N/A')
            series_uid = getattr(series, 'SeriesInstanceUID', 'N/A')
            series_desc = getattr(series, 'SeriesDescription', 'N/A')
            modality = getattr(series, 'Modality', 'N/A')
            num_images = len(series.children) if hasattr(series, 'children') else 0

            series_data.append({
                'num': series_num,
                'uid': series_uid,
                'desc': series_desc,
                'modality': modality,
                'images': num_images
            })

# Sort by series number
series_data.sort(key=lambda x: x['num'] if isinstance(x['num'], int) else 999)

print(f"{'Series #':<12} {'Description':<35} {'Images':<8} {'Series Instance UID'}")
print("-" * 100)

for s in series_data:
    # Truncate UID for display
    uid_display = s['uid'][:60] + "..." if len(s['uid']) > 60 else s['uid']
    print(f"{str(s['num']):<12} {s['desc']:<35} {s['images']:<8} {uid_display}")

print("\n" + "=" * 100)
print("KEY DIFFERENCES")
print("=" * 100)

print("""
┌─────────────────────┬──────────────────────────────┬────────────────────────────────────────┐
│ Aspect              │ SeriesNumber                 │ SeriesInstanceUID                      │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Type                │ Integer (1, 2, 3, ...)       │ Globally Unique Identifier (UID)       │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Format              │ Simple number                │ Dotted decimal notation                │
│                     │ Example: 15                  │ Example: 1.3.6.1.4.1.23849.4245587...  │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Uniqueness          │ Unique WITHIN a study        │ Globally unique across ALL systems     │
│                     │ (can repeat across studies)  │ (will never repeat anywhere)           │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Human-readable      │ Yes - easy to reference      │ No - very long string                  │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Assignment          │ Technician or scanner        │ Automatically generated by scanner     │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Can change?         │ Yes (if re-acquired)         │ No (permanently assigned at creation)  │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Ordering            │ Usually sequential           │ No inherent order                      │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ DICOM Tag           │ (0020,0011)                  │ (0020,000E)                            │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Best for            │ Human communication          │ Database indexing                      │
│                     │ "Please check series 15"     │ Linking related data                   │
│                     │ Quick identification         │ PACS queries                           │
├─────────────────────┼──────────────────────────────┼────────────────────────────────────────┤
│ Persistence         │ Low - may change on re-scan  │ High - permanent identifier            │
└─────────────────────┴──────────────────────────────┴────────────────────────────────────────┘
""")

print("\n" + "=" * 100)
print("PRACTICAL EXAMPLES")
print("=" * 100)

print("\n1. SCENARIO: Finding a specific sequence")
print("-" * 100)
print("   Human says: 'Look at series 15'")
print("   → Use SeriesNumber: Quick, easy, everyone understands")
print()
print("   PACS query: SELECT * FROM images WHERE SeriesInstanceUID = '1.3.6.1.4.1...'")
print("   → Use SeriesInstanceUID: Precise, no ambiguity across studies")

print("\n2. SCENARIO: Multiple studies for same patient")
print("-" * 100)
print("   Study 1 (Jan 2023): Series 5 = T1_STAGE")
print("   Study 2 (Jun 2023): Series 5 = T2_conv  ← SAME NUMBER, DIFFERENT SCAN")
print()
print("   → SeriesNumber is only unique WITHIN a study")
print("   → SeriesInstanceUID is unique across ALL scans ever")

print("\n3. SCENARIO: Ground truth CSV")
print("-" * 100)
print("   Your CSV lists: '1000C9D0 (#103)'")
print("   → #103 = SeriesNumber (the important part)")
print("   → 1000C9D0 = Folder ID (just organizational)")
print()
print("   Why not use SeriesInstanceUID in CSV?")
print("   → Too long and unwieldy for human review")
print("   → SeriesNumber is sufficient within a single study")

print("\n4. SCENARIO: Data merging/linking")
print("-" * 100)
print("   If you export/re-import data:")
print("   → SeriesNumber: Might change")
print("   → SeriesInstanceUID: Will remain the same")
print("   → Folder IDs (like 10011A2A): Will definitely change")

print("\n" + "=" * 100)
print("RECOMMENDATION FOR YOUR STUDY")
print("=" * 100)
print("""
✓ Use SeriesNumber for:
  • Ground truth CSV (human-readable)
  • Daily communication with radiologists
  • Quick identification in your pipeline
  • Your current approach is correct!

✓ Use SeriesInstanceUID for:
  • Database primary keys
  • Linking data across different exports
  • PACS queries
  • Long-term data provenance

✗ Don't rely on folder IDs (like 10011A2A):
  • Not portable across systems
  • Only exists in DICOMDIR
  • Will change if data is re-exported
""")

print("\n" + "=" * 100)
